version: '2'
services:
  suti-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/SuTi/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=SuTi
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
